<div>
	<span class="title">Create User</span>
	
	<form action="<?php echo $this->eprint($this->frac->createuri('staff/create')); ?>" method="post">
		<fieldset>
			<table>
				<tr>
					<td width="15%"><label for="nickname" class="bold">Username:</label></td>
					<td colspan="2" width="40%"><input type="text" name="nickname" maxlength="32" size="40" /></td>
					<td colspan="2" width="45%">The new user's username (and login name.)</td>
				</tr>
				<tr>
					<td><label for="password">Password:</label></td>
					<td colspan="2"><input type="password" name="password" size="35" /></td>
					<td colspan="2">The new user's password. (Optional, leave blank to generate a password.)</td>
				</tr>
				<tr>
					<td><label for="password2">Confirm:</label></td>
					<td colspan="2"><input type="password" name="password2" size="35" /></td>
					<td colspan="2">Confirmation password.</td>
				</tr>
				<tr>
					<td><label for="email" class="bold">E-mail:</td>
					<td colspan="2"><input type="text" name="email" maxlength="255" size="40" /></td>
					<td colspan="2">The user's e-mail. Note this should be valid as autogenerated passwords are sent here.</td>
				</tr>
				<tr>
					<td><label for="comment">Comment:</td>
					<td colspan="2"><input type="text" name="comment" maxlength="255" size="50" /></td>
					<td colspan="2">Optional user comment.</td>
				</tr>
				<tr>
					<td><label for="mobile">Mobile:</td>
					<td colspan="2"><input type="text" name="mobile" maxlength="32" size="25" /></td>
					<td colspan="2">User's cell phone number.</td>
				</tr>
				<tr>
					<td><label for="perm[]">Global Permissions:</label></td>
<?php for($h = 0; $h < 3; $h++): ?>
					<td>
<?php for($i = $h; $i < count($this->permissions); $i += 3): ?>
						<input type="checkbox" name="perm[]" value="<?php $this->eprint($this->permissions[$i][1]); ?>" /> <?php $this->eprint($this->permissions[$i][0]); ?><br />
<?php endfor; ?>
					</td>
<?php endfor; ?>
					<td width="27%">The user's <strong>global</strong> permissions. Project-specific permissions can be assigned after creation.</td>
				</tr>
				<tr>
					<td><input type="submit" value="Create User" /></td>
					<td colspan="2"><strong>Note:</strong> Required fields are indicated with <b>bold</b>.
				</tr>
			</table>
		</fieldset>
	</form>
</div>
